import pexpect

devices = [i for i in range(32897, 32922)]
id = 1
for port in devices:
    with pexpect.spawn('telnet 192.168.0.29 {}'.format(port)) as t:
        t.sendline()
        t.expect('no]:')
        print(t.before.decode('utf-8'))
        t.sendline('no')
        t.expect('Press RETURN to get started!')
        print(t.before.decode('utf-8'))
        t.sendline('\r\n')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('enable')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('conf t')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('no service config')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('hostname R{}'.format(str(id)))
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('interface e0/0')
        t.expect('[>#]')
        t.sendline('no shutdown')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('ip address 192.168.30.{} 255.255.255.0'.format(id))
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('username melhiour secret melhiour')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('enable secret melhiour')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('line vty 0 4')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('login local')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('transport input ssh telnet')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('ip domain-name py.hi')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('crypto key generate rsa modulus 2048')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('end')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        t.sendline('wr')
        t.expect('[>#]')
        print(t.before.decode('utf-8'))
        id = id + 1


    
